songs = [
["макс корж", "https://www.youtube.com/watch?v=napUAIh4UE0&list=RDEMY4sqqdkLKGnBo7VPdTGr4g&start_radio=1"],
["макс корж малиновый закат", "https://www.youtube.com/watch?v=Qv6GyNkqYfY"],
["ленинград кольщик", "https://www.youtube.com/watch?v=3zvTRQr7ns8"],
["егор крид сердцеедка", "https://www.youtube.com/watch?v=8dZVhRyTz8U"],
["монеточка каждый раз", "https://www.youtube.com/watch?v=8wLxWbJnPjE"],
["мияги минор", "https://www.youtube.com/watch?v=8P3oJz0yJrI"],
["мияги бруклин", "https://www.youtube.com/watch?v=mhwmB95EX1A"],
["капитан", "https://www.youtube.com/watch?v=8ZKvZJ3sYcM"],
["это любовь", "https://www.youtube.com/watch?v=wnj3zNd4FPQ"],
["между нами", "https://www.youtube.com/watch?v=dfPBOt_rhdw"],
["макс корж эндорфин", "https://www.youtube.com/watch?v=f5AjMRi9of8"],
["её виной", "https://www.youtube.com/watch?v=1RxtNtRiOqQ"],
["танцуй сама", "https://www.youtube.com/watch?v=fvYU6HyXvAk"],
["скриптонит", "https://www.youtube.com/watch?v=nkncpcanly0&list=RDEMDG7BqAYjmBpYql-exAx6fw&start_radio=1"],
["мияги", "https://www.youtube.com/watch?v=e_atyw0IDqg&list=RDEMjoqDo_hb-PWWiMNsIGEsEA&start_radio=1"],
["нервы", "https://www.youtube.com/watch?v=HwBt4UUmtYQ&list=RDEMpYP9mglW6ZsoteYdemTXfA&start_radio=1"],
["нервы батареи", "https://www.youtube.com/watch?v=oIE5WiJ9oow&list=RDEMpYP9mglW6ZsoteYdemTXfA&index=4"],
["нервы слишком влюблён", "https://www.youtube.com/watch?v=NagEv9GMtWI&list=RDEMpYP9mglW6ZsoteYdemTXfA&index=6"],
["нервы счастье", "https://www.youtube.com/watch?v=5EhG-_WckuQ&list=RDEMpYP9mglW6ZsoteYdemTXfA&index=7"],
["макс корж амстердам", "https://www.youtube.com/watch?v=BbxNcTJsR6M&list=RDEMpYP9mglW6ZsoteYdemTXfA&index=14"],
["нервы зажигалки", "https://www.youtube.com/watch?v=gwlfa9_3r_I&list=RDEMpYP9mglW6ZsoteYdemTXfA&index=30"],
["кис кис", "https://www.youtube.com/watch?v=QDJ6YqI3sjo&list=RDEMr8RfvyPQWAfppeRfgX1lOA&start_radio=1"],
["до зимы", "https://www.youtube.com/watch?v=VBpHMxmtHZo"],
["бетховен", "https://www.youtube.com/watch?v=mTTCj0bFuxw&list=RDEMiV30cZkQLMl8dvkOpVcP8g&start_radio=1"],
["моцарт", "https://www.youtube.com/watch?v=A8aFXctFtqE&list=PLG3Knu_wJfaF8srHFM5NluA9zZySJJBPE"]
]